Parameters:
  SubnetIds:
    Description: A comma-separated list of subnets to deploy Kubernetes nodes
    Type: String
    Default: subnet-00b11c9db587ef089,subnet-0b5c4a0614a3a8998
  
  DataS3BucketName:
    Type: String
    Description: Name for an S3 bucket to be created for processed data
    Default: data-adzd

Resources:
  KubernetesControlPlane:
    Type: "AWS::EKS::Cluster"
    DeletionPolicy: Delete
    Properties:
      Name: adzd-kubernetes-cluster
      RoleArn: !Join [ "", [ "arn:aws:iam::", !Ref "AWS::AccountId", ":role/LabRole" ] ]
      ResourcesVpcConfig:
        SubnetIds: !Split [ ",", !Ref SubnetIds]
  
  KubernetesNodeGroup:
    Type: AWS::EKS::Nodegroup
    DeletionPolicy: Delete
    Properties:
      ClusterName: !Ref KubernetesControlPlane
      NodeRole: !Join [ "", [ "arn:aws:iam::", !Ref "AWS::AccountId", ":role/LabRole" ] ]
      Subnets: !Split [ ",", !Ref SubnetIds]
      ScalingConfig:
        DesiredSize: 1
        MaxSize: 1
        MinSize: 1
      InstanceTypes: 
        - t3.small

  DataS3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref DataS3BucketName
      VersioningConfiguration:
        Status: Enabled
